# Generated by Django 3.1.4 on 2021-01-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_running'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='bound',
        ),
    ]
